### ISSUE TITLE
[feature] New plugins, widgets and Add-Ons list for adding

### ISSUE THREAD

**Issue by DimaMinka** [lukecav/awesome-elementor#2]
- [ ] [Elementor related plugins from elementor.com](https://docs.elementor.com/article/126-elementor-related-plugins)
- [ ] [Best Elementor add-ons fro athemes.com](https://athemes.com/collections/best-elementor-addons/)
- [ ] [Trello community resources for Elementor](https://trello.com/b/52NXAeg2/elementor-resources-for-and-by-the-community) 
- [ ] [Mihdan Elementor yandex maps](https://wordpress.org/plugins/mihdan-elementor-yandex-maps/)

**Comment by lukecav** [comment]
Please create a PR and include those.
https://help.github.com/articles/creating-a-pull-request/
