### ISSUE TITLE
Debug Error Elementor

### ISSUE THREAD

**Issue by cart13** [lukecav/awesome-elementor#3]
Who can help fix errors?
== Debug ==
	Errors: 
		TypeError: Cannot read property 'currentView' of undefined
			at wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.4 - 2:250776
			2018-12-12 10:42 +00:00

		TypeError: e.ui.loading.addClass is not a function
			at wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.2.4 - 2:36316
			2018-12-11 15:29 +00:00
			x 2 times

				
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10
	MySQL version: (Debian) v5.6.39-83.1
	PHP Version: 7.0.15
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.2
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.6.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Advanced Database Cleaner
		Version: 2.0.0
		Author: Younes JFR.

	Astra Pro
		Version: 1.6.9
		Author: Brainstorm Force

	Classic Editor
		Version: 1.3
		Author: WordPress Contributors

	Custom Sidebars
		Version: 3.2.2
		Author: WPMU DEV

	Elementor
		Version: 2.3.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.3.1
		Author: Elementor.com

	LuckyWP Table of Contents
		Version: 1.0.4
		Author: LuckyWP

	Query Monitor
		Version: 3.2.2
		Author: John Blackbourn & contributors

	Shortcodes Ultimate
		Version: 5.2.0
		Author: Vladimir Anokhin

	TablePress
		Version: 1.9.1
		Author: Tobias Bäthge

	TinyMCE Advanced
		Version: 4.8.2
		Author: Andrew Ozz

	UpdraftPlus - Backup/Restore
		Version: 1.16.0
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 3.5.3
		Author: Automattic

	WooCommerce Multilingual
		Version: 4.3.7
		Author: OnTheGoSystems

	WP Maintenance Mode
		Version: 2.2.2
		Author: Designmodo

	WPML Multilingual CMS
		Version: 4.1.2
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.9.1
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.7.1
		Author: OnTheGoSystems

**Comment by lukecav** [comment]
I would ask that question either here
https://github.com/pojome/elementor/issues/new/choose
or here
https://wordpress.org/support/plugin/elementor

This is a repo for Elementor plugins links and not Elementor support, best of luck.
