### ISSUE TITLE
Drag and drop dont work in elementor - error keeps turning up

### ISSUE THREAD

**Issue by lonerandrup** [lukecav/awesome-elementor#4]
JS: showing 1 of 1JS: 2019-12-17 16:35:15 [error X 5][https://lonerandrup.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.2:31:179309] Ugyldigt argument. 

When I wp advance clean and delete elementor and upload the plugin again everything is fine, when I then make a page the error turns up and i canot use drag and drop in elementor.

But I am not sure what to delete or replace in the system, under wp-content/plugins/elementor/assets/js/editor.min.js 

hope one of you can help me. ths. 

Best Lone

**Comment by lukecav** [comment]
You need to add that support request on the WordPress.org repo or as an issue on the actual GitHub repo.
https://wordpress.org/support/plugin/elementor/
https://github.com/elementor/elementor/issues/new/choose
