### ISSUE TITLE
Dynamic Visibility for Elementor hasn't been updated in more than 2 years now... I think it's been abandoned.

### ISSUE THREAD

**Issue by d19dotca** [lukecav/awesome-elementor#6]
Just a heads up that the "Dynamic Visibility for Elementor - Elementor plugin visibility" has been abandoned it seems, as the last update was over 2 years ago and WordPress repository even provides a warning on it due to it not having been tested with the latest 3 versions (though much more than that) of WordPress. May want to consider adding a warning to it in the list, or possibly even removing it.

**Comment by lukecav** [comment]
The plugin was updated two months ago.

https://wordpress.org/plugins/dynamic-visibility-for-elementor/#developers
https://plugins.trac.wordpress.org/changeset/2527203
